// Copyright 2010 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ioutil

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"
)

// Random number state.
// We generate random temporary file names so that there's a good
// chance the file doesn't exist yet - keeps the number of tries in
// TempFile to a minimum.
var rand uint32       // 种子
var randmu sync.Mutex // 锁

// 随机数种子 = 时间戳 + pid
func reseed() uint32 {
	return uint32(time.Now().UnixNano() + int64(os.Getpid()))
}

func nextRandom() string {
	randmu.Lock()

	// 获取种子
	r := rand
	if r == 0 {
		r = reseed()
	}

	// 计算下一种子
	r = r*1664525 + 1013904223 // constants from Numerical Recipes
	rand = r

	randmu.Unlock()

	// 数字转字符串
	return strconv.Itoa(int(1e9 + r%1e9))[1:]
}

// TempFile creates a new temporary file in the directory dir,
// opens the file for reading and writing, and returns the resulting *os.File.
// The filename is generated by taking pattern and adding a random
// string to the end. If pattern includes a "*", the random string
// replaces the last "*".
// If dir is the empty string, TempFile uses the default directory
// for temporary files (see os.TempDir).
// Multiple programs calling TempFile simultaneously
// will not choose the same file. The caller can use f.Name()
// to find the pathname of the file. It is the caller's responsibility
// to remove the file when no longer needed.
func TempFile(dir, pattern string) (f *os.File, err error) {
	if dir == "" {
		// 默认取临时目录
		dir = os.TempDir()
	}

	// 找前缀和后缀
	var prefix, suffix string
	if pos := strings.LastIndex(pattern, "*"); pos != -1 {
		prefix, suffix = pattern[:pos], pattern[pos+1:]
	} else {
		prefix = pattern
	}

	nconflict := 0
	for i := 0; i < 10000; i++ {
		// 新文件
		name := filepath.Join(dir, prefix+nextRandom()+suffix)

		// 打开文件
		f, err = os.OpenFile(name, os.O_RDWR|os.O_CREATE|os.O_EXCL, 0600)
		if os.IsExist(err) {
			// 已经存在
			if nconflict++; nconflict > 10 {
				// 冲突数过大时，重置随机种子
				randmu.Lock()
				rand = reseed()
				randmu.Unlock()
			}

			// 冲突了，继续
			continue
		}

		// 成功 或 失败
		break
	}

	return
}

// TempDir creates a new temporary directory in the directory dir
// with a name beginning with prefix and returns the path of the
// new directory. If dir is the empty string, TempDir uses the
// default directory for temporary files (see os.TempDir).
// Multiple programs calling TempDir simultaneously
// will not choose the same directory. It is the caller's responsibility
// to remove the directory when no longer needed.
func TempDir(dir, prefix string) (name string, err error) {
	if dir == "" {
		// 默认临时目录
		dir = os.TempDir()
	}

	nconflict := 0
	for i := 0; i < 10000; i++ {
		// 新目录
		try := filepath.Join(dir, prefix+nextRandom())

		// 创建目录
		err = os.Mkdir(try, 0700)
		if os.IsExist(err) {
			// 已经存在

			if nconflict++; nconflict > 10 {
				// 冲突数过大时，重置随机种子
				randmu.Lock()
				rand = reseed()
				randmu.Unlock()
			}

			// 继续
			continue
		}

		if os.IsNotExist(err) {
			// 不存在，再次确认一下
			if _, err := os.Stat(dir); os.IsNotExist(err) {
				// 真的创建失败
				return "", err
			}
		}

		// 成功 或者 失败
		if err == nil {
			name = try
		}

		break
	}

	return
}
